services:
  registry:
    image: registry:2
    ports:
      - "5004:5000"
    volumes:
      - registry:/var/lib/registry
    restart: unless-stopped
    environment:
      REGISTRY_PROXY_REMOTEURL: https://registry-1.docker.io

volumes:
  registry:
